<?php
namespace App\Helpers;

class FormPs2
{
    static function formPs2PanelPhAocc()
    {
        // DATA INI DINAMIS! - JANGAN DIUBAH!
        $data['panelLvmdps'] = [
            [
                'group' => 'panel_lvmdp',
                'modul' => '+NO1',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => ['MANUAL', 'AUTO'],
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'INCOMING PS 2 A/BUS A',
            ],
            [
                'group' => 'panel_lvmdp',
                'modul' => '+NO2',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'INCOMING GENSET (BYPASS)',
            ],
            [
                'group' => 'panel_lvmdp',
                'modul' => '+NO3',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'BYPASS UPS A',
            ],
            [
                'group' => 'panel_lvmdp',
                'modul' => '+NO4',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'MODUL LVMDP',
            ],
            [
                'group' => 'panel_lvmdp',
                'modul' => '+NO5',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => ['MANUAL', 'AUTO'],
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'BUS COUPLER',
            ],
            [
                'group' => 'panel_lvmdp',
                'modul' => '+NO6',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'MODUL LVMDP',
            ],
            [
                'group' => 'panel_lvmdp',
                'modul' => '+NO7',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'INCOMING BUS B',
            ],
        ];
        $data['panelActsGensets'] = [
            [
                'group' => 'panel_acts_genset',
                'modul' => '+NO1',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => ['MANUAL', 'AUTO'],
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'INCOMING PS 2 B',
            ],
            [
                'group' => 'panel_acts_genset',
                'modul' => '+NO2',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'INCOMING ACTS',
            ],
            [
                'group' => 'panel_acts_genset',
                'modul' => '+NO3',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'PANEL ACTS',
            ],
            [
                'group' => 'panel_acts_genset',
                'modul' => '+NO4',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'ACTS - GENSET',
            ],
            [
                'group' => 'panel_acts_genset',
                'modul' => '+NO5',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'GENSET - BUS A (BYPASS)',
            ],
            [
                'group' => 'panel_acts_genset',
                'modul' => '+NO6',
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'local_remote' => ['LOCAL', 'REMOTE'],
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => ['LOCAL', 'REMOTE'],
                'tegangan_v_1' => '',
                'tegangan_v_2' => '',
                'tegangan_v_3' => '',
                'arus_1' => '',
                'arus_2' => '',
                'arus_3' => '',
                'daya_1' => '',
                'daya_2' => '',
                'daya_3' => '',
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => null,
                'keterangan' => 'PPG GENSET',
            ],
        ];

        $data['acts'] = [
            [
                'group' => 'acts',
                'modul' => '+NO3',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => ['OPEN', 'CLOSE'],
                'tegangan' => ['ADA', 'TIDAK'],
                'transfer_switch' => ['OPEN', 'CLOSE'],
                'posisi_mccb' => null,
                'keterangan' => 'GENSET ACTS',
            ],
        ];

        $data['mainDistributionPanels'] = [
            [
                'group' => 'main_distribution_panel',
                'modul' => '+NO4.4',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => ['OPEN', 'CLOSE'],
                'keterangan' => 'UPS A',
            ],
            [
                'group' => 'main_distribution_panel',
                'modul' => '+NO4.5',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => ['OPEN', 'CLOSE'],
                'keterangan' => 'SDP AOCC',
            ],
            [
                'group' => 'main_distribution_panel',
                'modul' => '+NO4.6',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => ['OPEN', 'CLOSE'],
                'keterangan' => 'SDP PH AOCC',
            ],
            [
                'group' => 'main_distribution_panel',
                'modul' => '+NO6.3',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => ['OPEN', 'CLOSE'],
                'keterangan' => 'BYPASS UPS B',
            ],
            [
                'group' => 'main_distribution_panel',
                'modul' => '+NO6.4',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => ['OPEN', 'CLOSE'],
                'keterangan' => 'UPS B',
            ],
            [
                'group' => 'main_distribution_panel',
                'modul' => '+NO6.5',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => ['OPEN', 'CLOSE'],
                'keterangan' => 'SDP AOCC',
            ],
            [
                'group' => 'main_distribution_panel',
                'modul' => '+NO6.6',
                'posisi_cb' => null,
                'cb_spring' => null,
                'local_remote' => null,
                'mode_kontrol_modul' => null,
                'mode_kontrol_scada' => null,
                'tegangan_v_1' => null,
                'tegangan_v_2' => null,
                'tegangan_v_3' => null,
                'arus_1' => null,
                'arus_2' => null,
                'arus_3' => null,
                'daya_1' => null,
                'daya_2' => null,
                'daya_3' => null,
                'normal_source' => null,
                'tegangan' => null,
                'transfer_switch' => null,
                'posisi_mccb' => ['OPEN', 'CLOSE'],
                'keterangan' => 'SDP PH AOCC',
            ],
        ];
        return (object) $data;
    }

    static function formPs2ChecklistPanelLvHarian()
    {
        $data['incoming1'] = [
            [
                'cubicle' => 'INCOMING I',
                'peralatan' => 'ACB 3200 A',
                'merek' => 'ABB',
                'tipe' => 'SACE EMAX 2',
                'keterangan' => '',
            ]
        ];

        $data['rak1'] = [
            [
                'cubicle' => 'RAK I',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'UPS 005B',
            ],
            [
                'cubicle' => 'RAK I',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP 001B Lantai 2',
            ],
            [
                'cubicle' => 'RAK I',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'UPS 005A',
            ],
            [
                'cubicle' => 'RAK I',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP AC 002',
            ],
            [
                'cubicle' => 'RAK I',
                'peralatan' => 'MCCB 63 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'Fuel System Ground Tank',
            ],
            [
                'cubicle' => 'RAK I',
                'peralatan' => 'MCCB 16 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'Power Meter Trafo Aux',
            ]
        ];

        $data['rak2'] = [
            [
                'cubicle' => 'RAK II',
                'peralatan' => 'MCCB 32 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'Rectifier B',
            ],
            [
                'cubicle' => 'RAK II',
                'peralatan' => 'MCCB 80 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP 001A Ruang Panel',
            ],
            [
                'cubicle' => 'RAK II',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP 001C Ruang Genset',
            ],
            [
                'cubicle' => 'RAK II',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SPARE',
            ],
            [
                'cubicle' => 'RAK II',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'REKLAME',
            ],
            [
                'cubicle' => 'RAK II',
                'peralatan' => 'MCCB 200 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'Panel Charging',
            ]
        ];

        $data['coupler'] = [
            [
                'cubicle' => 'COUPLER',
                'peralatan' => 'ACB 1600 A',
                'merek' => 'ABB',
                'tipe' => 'SACE EMAX 2',
                'keterangan' => '',
            ]
        ];

        $data['incoming2'] = [
            [
                'cubicle' => 'INCOMING II',
                'peralatan' => 'MCCB 3200 A',
                'merek' => 'ABB',
                'tipe' => 'SACE EMAX 2',
                'keterangan' => '',
            ]
        ];

        $data['rak3'] = [
            [
                'cubicle' => 'RAK III',
                'peralatan' => 'MCCB 32 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP 007 Ruan Genset',
            ],
            [
                'cubicle' => 'RAK III',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP 008 Ruang Genset',
            ],
            [
                'cubicle' => 'RAK III',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP 006 Ruang Genset',
            ],
            [
                'cubicle' => 'RAK III',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'Rectifier A',
            ],
            [
                'cubicle' => 'RAK III',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SPARE',
            ],
            [
                'cubicle' => 'RAK III',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP AC LT 2',
            ]
        ];

        $data['rak4'] = [
            [
                'cubicle' => 'RAK IV',
                'peralatan' => 'MCCB 32 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP 003 GH 128',
            ],
            [
                'cubicle' => 'RAK IV',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'UPS 005B Ruang Server',
            ],
            [
                'cubicle' => 'RAK IV',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'UPS 005A Ruang Server',
            ],
            [
                'cubicle' => 'RAK IV',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'Penerangan Ground Tank',
            ],
            [
                'cubicle' => 'RAK IV',
                'peralatan' => 'MCCB 160 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SDP 002B Ruang Server',
            ],
            [
                'cubicle' => 'RAK IV',
                'peralatan' => 'MCCB 32 A',
                'merek' => 'ABB',
                'tipe' => 'SACE TMAX',
                'keterangan' => 'SPARE',
            ]
        ];

        $data['panelOutGoingAocc'] = [
            [
                'cubicle' => 'Panel Outgoing AOCC',
                'peralatan' => 'ACB 1250 A',
                'merek' => 'ABB',
                'tipe' => 'SACE EMAX 2',
                'keterangan' => '',
            ],
            [
                'cubicle' => 'Panel Outgoing AOCC',
                'peralatan' => 'ACB 1250 A',
                'merek' => 'ABB',
                'tipe' => 'SACE EMAX 2',
                'keterangan' => '',
            ]
        ];

        return (object) $data;
    }

    static function formPs2PemeliharaanEnamBulanan()
    {
        $data['panelMv20Kvs'] = [
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN LAMPU INDIKATOR PANEL',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN LAMPU INDIKATOR TM',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN INDIKATOR SF6',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN PARA METER TEGANGAN, ARUS, FAKTOR DAYA, DAN LAINYA',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN MCB/FUSE  DAN TEGANGAN KONTROL 24/48/110/220',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN BUNYI-BUNYI SUARA TIDAK NORMAL, BAU DAN LAINNYA',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN &  MEMBERSIHKAN COMPARTEMENT KONTROL',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & MEMBERSIHKAN COMPARTEMENT DS/CB/EARTHING',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & MEMBERSIHKAN COMPARTEMENT KABEL',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN KEKENCANGAN TERMINAL KABEL KONTROL',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & PEMBERIAN GREASE MEKANIS',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN TAHANAN COIL CLOSING (16,9 W)',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN TAHANAN COIL TRIPPING/OPEN (16,9 W)',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & PENGUJIAN CLOSING DENGAN MEKANIS & ELEKTRIK',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & PENGUJIAN OPEN/TRIPPING DENGAN MEKANIS & ELEKTRIK',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & PENGUJIAN STATUS INDIKASI PANEL',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'LOKAL',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'REMOTE',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'DS OPEN',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'DS CLOSE',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'CB OPEN',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'CB CLOSE',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'EARTHING CLOSE',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'EARTHING OPEN',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & KONDISI FISIK BAGIAN DALAM & LUAR PANEL',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN SISTEM PENTANAHAN',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & PENGUJIAN TAHANAN ISOLASI KABEL (GW)',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'L1 - G',
                'panel_1' => false,
                'panel_2' => false,
                'panel_3' => false,
                'giga_ohm' => true,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'L2 - G',
                'panel_1' => false,
                'panel_2' => false,
                'panel_3' => false,
                'giga_ohm' => true,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'L3 - G',
                'panel_1' => false,
                'panel_2' => false,
                'panel_3' => false,
                'giga_ohm' => true,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'MEMBERSIHKAN & MERAPIKAN AREA SEKITAR PERALATAN',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'PANEL MV 20 KV',
                'spesifikasi_pemeliharaan' => 'SELESAI PEKERJAAN PERALATAN NORMAL OPERASI',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ]
        ];

        $data['kabel20Kvs'] = [
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN KONDISI FISIK BAGIAN LUAR KABEL',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN KONDISI PEMEGANG KABEL (KABEL TRAY, BAUT, KLEM DAN LAINYA)',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN KONDISI TERMINAL SAMBUNGAN KABEL (PLUG IN)',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'PEMERIKSAAN & PENGUJIAN TAHANAN ISOLASI KABEL (GW)',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'L1 - G',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'L2 - G',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'L3 - G',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'L1 - L2',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'L2 - L3',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'L1 - L3',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'MEMBERSIHKAN & MERAPIKAN AREA SEKITAR PERALATAN',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
            [
                'group_spesifikasi_pemeliharaan' => 'KABEL 20 KV',
                'spesifikasi_pemeliharaan' => 'SELESAI PEKERJAAN PERALATAN NORMAL OPERASI',
                'panel_1' => true,
                'panel_2' => true,
                'panel_3' => true,
                'giga_ohm' => false,
            ],
        ];
        
        return (object) $data;
    }
}
