<?php

namespace App\Helpers;

class FormPs1
{
    static function formPs1PanelTRDuaMingguan()
    {
        $data['columns'] = [['title' => 'R', 'name' => 'q1'], ['title' => 'S', 'name' => 'q2'], ['title' => 'T', 'name' => 'q3']];
        $data['panelNp0s'] = [['name' => 'lampu_indikator', 'pertanyaan' => 'Lampu Indikator', 'satuan' => ['Normal', 'Abnormal']], ['name' => 'tegangan', 'pertanyaan' => 'Tegangan', 'satuan' => 'Volt'], ['name' => 'arus', 'pertanyaan' => 'Arus', 'satuan' => 'A'], ['name' => 'frekwensi', 'pertanyaan' => 'Frekwensi', 'satuan' => 'Hz'], ['name' => 'power_factor', 'pertanyaan' => 'Power Factor', 'satuan' => 'pf'], ['name' => 'posisi_cb_incoming', 'pertanyaan' => 'Posisi CB incoming', 'satuan' => ['Open', 'Close']], ['name' => 'kondisi_power_meter', 'pertanyaan' => 'Kondisi Power Meter', 'satuan' => ['Normal', 'Abnormal']], ['name' => 'tegangan_kontrol', 'pertanyaan' => 'Tegangan Kontrol', 'satuan' => 'VDC'], ['name' => 'mcb_fuse_kontrol', 'pertanyaan' => 'MCB/Fuse kontrol', 'satuan' => ['Normal', 'Abnormal']], ['name' => 'nilai_arus_bocor', 'pertanyaan' => 'Nilai Arus Bocor (Ir)', 'satuan' => 'A']];

        $data['panelT0s'] = [
            ['name' => 'lampu_indikator', 'pertanyaan' => 'Lampu Indikator', 'satuan' => ['Normal', 'Abnormal']],
            ['name' => 'tegangan', 'pertanyaan' => 'Tegangan', 'satuan' => 'Volt'],
            ['name' => 'arus', 'pertanyaan' => 'Arus', 'satuan' => 'A'],
            ['name' => 'frekwensi', 'pertanyaan' => 'Frekwensi', 'satuan' => 'Hz'],
            ['name' => 'power_factor', 'pertanyaan' => 'Power Factor', 'satuan' => 'pf'],
            ['name' => 'posisi_cb_incoming_a', 'pertanyaan' => 'Posisi CB incoming A', 'satuan' => ['Open', 'Close']],
            ['name' => 'posisi_cb_incoming_b', 'pertanyaan' => 'Posisi CB incoming B', 'satuan' => ['Open', 'Close']],
            ['name' => 'kondisi_power_meter', 'pertanyaan' => 'Kondisi Power Meter', 'satuan' => ['Normal', 'Abnormal']],
            ['name' => 'tegangan_kontrol', 'pertanyaan' => 'Tegangan Kontrol', 'satuan' => 'VDC'],
            ['name' => 'mcb_fuse_kontrol', 'pertanyaan' => 'MCB/Fuse kontrol', 'satuan' => ['Normal', 'Abnormal']],
            ['name' => 'nilai_arus_bocor', 'pertanyaan' => 'Nilai Arus Bocor (Ir)', 'satuan' => 'A'],
        ];

        return (object) $data;
    }

    static function formPs1PanelHarian()
    {
        // 'name' => ['cubicle', 'local', 'posisi_ds', 'posisi_grounding', 'posisi_cb', 'cb_spring', 'sf6_lev', 'tegangan', 'arus', 'cos', 'freq', 'daya', 'keterangan'],
        $data['title'] = ['CUBICLE', 'LOCAL/REMOTE', 'POSISI\nDS', 'POSISI\nGROUNDING', 'POSISI\nCB', 'CB\nSpring', 'SF6 LEV', 'TEGANGAN\n(KV)', 'ARUS\n(A)', 'COS\nPHI', 'FREQ\n(HZ)', 'DAYA\n(MW)', 'KETERANGAN'];
        $data['exts'] = [
            [
                    'cublicle' => 'MBC',
                    'local_remote' => ['LOCAL', 'REMOTE'],
                    'posisi_ds' => ['OPEN', 'CLOSE'],
                    'posisi_grounding' => ['OPEN', 'CLOSE'],
                    'posisi_cb' => ['OPEN', 'CLOSE'],
                    'cb_spring' => ['CHARGE', 'DISCHARGE'],
                    'sf6_lev' => ['R', 'G'],
                    'tegangan' => null,
                    'arus' => null,
                    'cos_phi' => null,
                    'freq' => null,
                    'daya' => null,
                    'keterangan' => null,
            ],
            [   
                'cublicle' => 'MCC',
                'local_remote' => null,
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => null,
                'cb_spring' => null,
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSD',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSE',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
        ];

        $data['er2as'] = [
            [
                'cublicle' => 'MCA',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MCB',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MCC',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSA',
                'local_remote' => null,
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => null,
                'cb_spring' => null,
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSB',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => null,
                'cb_spring' => null,
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSC',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSD',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSE',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSF',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSG',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSH',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSI',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSJ',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSK',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSL',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MCF',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
        ];

        $data['er2bs'] = [
            [
                'cublicle' => 'MCD',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MCE',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MCC',
                'local_remote' => null,
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => null,
                'cb_spring' => null,
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSX',
                'local_remote' => null,
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => null,
                'cb_spring' => null,
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSW',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSV',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSU',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MST',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSS',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSR',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSQ',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSP',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSO',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSN',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSM',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MCG',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
        ];

        $data['er1bs'] = [
            [
                'cublicle' => 'XSA',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XSB',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCA',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'MSA',
                'local_remote' => null,
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => null,
                'cb_spring' => null,
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
        ];

        $data['panel_mv_gensets'] = [
            [
                'cublicle' => 'XDA',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XDB',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
        ];

        $data['panel_mv_gensets'] = [
            [
                'cublicle' => 'XDA',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XDB',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
        ];

        $data['er1as'] = [
            [
                'cublicle' => 'XSK',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCM',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCN',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
        ];

        $data['er6s'] = [
            [
                'cublicle' => 'XCA',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCB',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCD',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCE',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCM',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCN',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XSP',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XSQ',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCR',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
            [
                'cublicle' => 'XCS',
                'local_remote' => ['LOCAL', 'REMOTE'],
                'posisi_ds' => ['OPEN', 'CLOSE'],
                'posisi_grounding' => ['OPEN', 'CLOSE'],
                'posisi_cb' => ['OPEN', 'CLOSE'],
                'cb_spring' => ['CHARGE', 'DISCHARGE'],
                'sf6_lev' => ['R', 'G'],
                'tegangan' => null,
                'arus' => null,
                'cos_phi' => null,
                'freq' => null,
                'daya' => null,
                'keterangan' => null,
            ],
        ];

        return (object) $data;
    }
    
    static function formPs1PanelTrAuxDuaMingguan()
    {
        $data['columnPanelADanBs'] = [['title' => 'R', 'name' => 'q1'],  ['title' => 'S', 'name' => 'q2'], ['title' => 'T', 'name' => 'q3']];
        $data['columnPanelSdps'] = [['title' => 'SDP2', 'name' => 'q4'], ['title' => 'SDP3A', 'name' => 'q5'], ['title' => 'SDP3B', 'name' => 'q6'], ['title' => 'SDP4', 'name' => 'q7']];

        $data['panelADanBs'] = [
            ['name' => 'lampu_indikator', 'pertanyaan' => 'Lampu Indikator', 'satuan' => ['Normal', 'Rusak']], 
            ['name' => 'tegangan', 'pertanyaan' => 'Tegangan', 'satuan' => 'Volt'], 
            ['name' => 'arus', 'pertanyaan' => 'Arus', 'satuan' => 'A'], 
            ['name' => 'frekwensi', 'pertanyaan' => 'Frekwensi', 'satuan' => 'Hz'], 
            ['name' => 'power_factor', 'pertanyaan' => 'Power Factor', 'satuan' => 'pf'], 
            ['name' => 'posisi_cb_incoming_a', 'pertanyaan' => 'Posisi CB incoming A', 'satuan' => ['Open', 'Close']], 
            ['name' => 'posisi_cb_incoming_b', 'pertanyaan' => 'Posisi CB incoming B', 'satuan' => ['Open', 'Close']], 
            ['name' => 'posisi_cb_coupler', 'pertanyaan' => 'Posisi CB Coupler', 'satuan' => ['Open', 'Close']], 
            ['name' => 'kondisi_power_meter', 'pertanyaan' => 'Kondisi Power Meter', 'satuan' => ['Normal', 'Error']], 
            ['name' => 'tegangan_kontrol', 'pertanyaan' => 'Tegangan Kontrol', 'satuan' => 'VDC'], 
            ['name' => 'mcb_fuse_kontrol', 'pertanyaan' => 'MCB/Fuse kontrol', 'satuan' => 'Normal'], 
            ['name' => 'nilai_arus_bocor_ir', 'pertanyaan' => 'Nilai Arus Bocor (Ir)', 'satuan' => 'A'] 
        ];
        $data['panelSdps'] = [
            ['name' => 'lampu_indikator', 'pertanyaan' => 'Lampu Indikator', 'satuan' => ['Normal', 'Rusak']],
            ['name' => 'tegangan_incoming', 'pertanyaan' => 'Tegangan Incoming', 'satuan' => 'Volt'],
            ['name' => 'arus', 'pertanyaan' => 'Arus', 'satuan' => 'A'],
            ['name' => 'frekwensi', 'pertanyaan' => 'Frekwensi', 'satuan' => 'Hz'],
            ['name' => 'posisi_cb_incoming', 'pertanyaan' => 'Posisi CB incoming', 'satuan' => ['Open', 'Close']],
            ['name' => 'mode_operasi_panel', 'pertanyaan' => 'Mode operasi panel', 'satuan' => ['Auto', 'Man']],
            ['name' => 'kondisi_metering', 'pertanyaan' => 'Kondisi Metering', 'satuan' => ['Normal', 'Error']],
            ['name' => 'mcb_fuse_kontrol', 'pertanyaan' => 'MCB/Fuse kontrol', 'satuan' => 'Normal']
        ];

        return (object) $data;
    }

    static function formPs1PanelTrAuxEnamBulanan()
    {
        $data['columnPanelADanBs'] = [['title' => 'R', 'name' => 'q1'], ['title' => 'S', 'name' => 'q2'], ['title' => 'T', 'name' => 'q3']];
        $data['columnPanelSdps'] = [['title' => 'SDP2', 'name' => 'q4'], ['title' => 'SDP3A', 'name' => 'q5'], ['title' => 'SDP3B', 'name' => 'q6'], ['title' => 'SDP4', 'name' => 'q7']];

        $data['panelADanBs'] = [
            ['name' => 'lampu_indikator', 'pertanyaan' => 'Lampu Indikator', 'satuan' => ['Normal', 'Rusak']], 
            ['name' => 'tegangan', 'pertanyaan' => 'Tegangan', 'satuan' => 'Volt'], 
            ['name' => 'arus', 'pertanyaan' => 'Arus', 'satuan' => 'A'], 
            ['name' => 'frekwensi', 'pertanyaan' => 'Frekwensi', 'satuan' => 'Hz'], 
            ['name' => 'power_factor', 'pertanyaan' => 'Power Factor', 'satuan' => 'pf'], 
            ['name' => 'posisi_cb_incoming_a', 'pertanyaan' => 'Posisi CB incoming A', 'satuan' => ['Open', 'Close']], 
            ['name' => 'posisi_cb_incoming_b', 'pertanyaan' => 'Posisi CB incoming B', 'satuan' => ['Open', 'Close']], 
            ['name' => 'posisi_cb_coupler', 'pertanyaan' => 'Posisi CB Coupler', 'satuan' => ['Open', 'Close']], 
            ['name' => 'kondisi_power_meter', 'pertanyaan' => 'Kondisi Power Meter', 'satuan' => ['Normal', 'Error']], 
            ['name' => 'tegangan_kontrol', 'pertanyaan' => 'Tegangan Kontrol', 'satuan' => 'VDC'], 
            ['name' => 'mcb_fuse_kontrol', 'pertanyaan' => 'MCB/Fuse kontrol', 'satuan' => 'Normal'], 
            ['name' => 'nilai_arus_bocor_ir', 'pertanyaan' => 'Nilai Arus Bocor (Ir)', 'satuan' => 'A'] 
        ];
        $data['panelSdps'] = [
            ['name' => 'lampu_indikator', 'pertanyaan' => 'Lampu Indikator', 'satuan' => ['Normal', 'Rusak']],
            ['name' => 'tegangan_incoming', 'pertanyaan' => 'Tegangan Incoming', 'satuan' => 'Volt'],
            ['name' => 'arus', 'pertanyaan' => 'Arus', 'satuan' => 'A'],
            ['name' => 'frekwensi', 'pertanyaan' => 'Frekwensi', 'satuan' => 'Hz'],
            ['name' => 'posisi_cb_incoming', 'pertanyaan' => 'Posisi CB incoming', 'satuan' => ['Open', 'Close']],
            ['name' => 'mode_operasi_panel', 'pertanyaan' => 'Mode operasi panel', 'satuan' => ['Auto', 'Man']],
            ['name' => 'kondisi_metering', 'pertanyaan' => 'Kondisi Metering', 'satuan' => ['Normal', 'Error']],
            ['name' => 'mcb_fuse_kontrol', 'pertanyaan' => 'MCB/Fuse kontrol', 'satuan' => 'Normal']
        ];

        return (object) $data;
    }

    static function formPs1PanelTrAuxTahunan()
    {
        $data['columnPanelADanBs'] = [['title' => 'R', 'name' => 'q1'], ['title' => 'S', 'name' => 'q2'], ['title' => 'T', 'name' => 'q3']];
        $data['columnPanelSdps'] = [['title' => 'SDP2', 'name' => 'q4'], ['title' => 'SDP3A', 'name' => 'q5'], ['title' => 'SDP3B', 'name' => 'q6'], ['title' => 'SDP4', 'name' => 'q7']];

        $data['panelADanBs'] = [
            ['name' => 'lampu_indikator', 'pertanyaan' => 'Lampu Indikator', 'satuan' => ['Normal', 'Rusak']], 
            ['name' => 'tegangan', 'pertanyaan' => 'Tegangan', 'satuan' => 'Volt'], 
            ['name' => 'arus', 'pertanyaan' => 'Arus', 'satuan' => 'A'], 
            ['name' => 'frekwensi', 'pertanyaan' => 'Frekwensi', 'satuan' => 'Hz'], 
            ['name' => 'power_factor', 'pertanyaan' => 'Power Factor', 'satuan' => 'pf'], 
            ['name' => 'posisi_cb_incoming_a', 'pertanyaan' => 'Posisi CB incoming A', 'satuan' => ['Open', 'Close']], 
            ['name' => 'posisi_cb_incoming_b', 'pertanyaan' => 'Posisi CB incoming B', 'satuan' => ['Open', 'Close']], 
            ['name' => 'posisi_cb_coupler', 'pertanyaan' => 'Posisi CB Coupler', 'satuan' => ['Open', 'Close']], 
            ['name' => 'kondisi_power_meter', 'pertanyaan' => 'Kondisi Power Meter', 'satuan' => ['Normal', 'Error']], 
            ['name' => 'tegangan_kontrol', 'pertanyaan' => 'Tegangan Kontrol', 'satuan' => 'VDC'], 
            ['name' => 'mcb_fuse_kontrol', 'pertanyaan' => 'MCB/Fuse kontrol', 'satuan' => 'Normal'], 
            ['name' => 'nilai_arus_bocor_ir', 'pertanyaan' => 'Nilai Arus Bocor (Ir)', 'satuan' => 'A'] 
        ];
        $data['panelSdps'] = [
            ['name' => 'lampu_indikator', 'pertanyaan' => 'Lampu Indikator', 'satuan' => ['Normal', 'Rusak']],
            ['name' => 'tegangan_incoming', 'pertanyaan' => 'Tegangan Incoming', 'satuan' => 'Volt'],
            ['name' => 'arus', 'pertanyaan' => 'Arus', 'satuan' => 'A'],
            ['name' => 'frekwensi', 'pertanyaan' => 'Frekwensi', 'satuan' => 'Hz'],
            ['name' => 'posisi_cb_incoming', 'pertanyaan' => 'Posisi CB incoming', 'satuan' => ['Open', 'Close']],
            ['name' => 'mode_operasi_panel', 'pertanyaan' => 'Mode operasi panel', 'satuan' => ['Auto', 'Man']],
            ['name' => 'kondisi_metering', 'pertanyaan' => 'Kondisi Metering', 'satuan' => ['Normal', 'Error']],
            ['name' => 'mcb_fuse_kontrol', 'pertanyaan' => 'MCB/Fuse kontrol', 'satuan' => 'Normal']
        ];

        return (object) $data;
    }
}